package com.hongxiang.kforthirtysix.logsql;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "LOG".
 */
public class Log {

    private Long id;
    private String user;
    private String key;

    public Log() {
    }

    public Log(Long id) {
        this.id = id;
    }

    public Log(Long id, String user, String key) {
        this.id = id;
        this.user = user;
        this.key = key;
    }

    public Log(String user, String key) {
        this.user = user;
        this.key = key;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

}
